### ISSUE TITLE
Update to Redmine 5.0.6 breaks bundle exec rake step in periodictask

### ISSUE THREAD

**Issue by NaturePinks** [jperelli/Redmine-Periodic-Task#115]
When upgrading to redmine 5.0.6 from 5.0.5, the following command in installation causes an error. 
However periodictask is still working in the application.

`bundle exec rake redmine:plugins:migrate NAME=periodictask RAILS_ENV=production`

```
/var/lib/gems/3.0.0/gems/bundler-2.4.3/lib/bundler/rubygems_integration.rb:304:in `block in replace_bin_path': can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
        from /var/lib/gems/3.0.0/gems/bundler-2.4.3/lib/bundler/rubygems_integration.rb:332:in `block in replace_bin_path'
        from /usr/bin/rake:25:in `<main>'
```

I tried adding rake to plugin's gem file and did a bundle install.
Now the bundle exec rake command gives error as:

```
rake aborted!
LoadError: cannot load such file -- rails
/home/redmine/redmine-5.0.6/config/application.rb:5:in `require'
/home/redmine/redmine-5.0.6/config/application.rb:5:in `<top (required)>'
/home/redmine/redmine-5.0.6/Rakefile:5:in `require'
/home/redmine/redmine-5.0.6/Rakefile:5:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
```
Any ideas please?

```
Environment:
  Redmine version                5.0.6.stable
  Ruby version                   3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  6.1.7.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Alternate
SCM:
  Git                            2.34.1
  Filesystem                     
Redmine plugins:
  periodictask                   4.1.0
```

**Comment by yzzy** [comment]
First, if you have Redmine with some plugins installed and you decide to update Redmine but there's no new version of these plugins, there's no need to execute `redmine:plugins:migrate` task. That's why periodictask is still working after Redmine update.
Second, `bundle exec rake/rails` is the most common way to execute Ruby code within bundled environment. But depending on your distro/containers/Redmine installation these commands may be different. Moreover with latest Rails versions you should `bundle exec rails ...` instead of `bundle exec rake ...`. So remove rake from plugin's gem file and issue form `${REDMINE_ROOT}`
```
bundle exec rails redmine:plugins:migrate NAME=periodictask RAILS_ENV=production
``` 
or
```
bin/rails redmine:plugins:migrate NAME=periodictask RAILS_ENV=production
```
HTH

**Comment by NaturePinks** [comment]
Thank  you @yzzy, for helping out. The command has run  without error.
