### ISSUE TITLE
Error on delete periodic tasks

### ISSUE THREAD

**Issue by marczona** [jperelli/Redmine-Periodic-Task#21]
When I hit the "delete" button I get an error message "page not found"

I think I located the problem: config/routes.rb contains "delete" as method for action destroy, but app/views/periodictask/index.html.erb uses "post" as method.

my fix to solve the problem: change method in app/views/periodictask/index.html.erb to delete

```
# diff ~/periodictask-unchanged/app/views/periodictask/index.html.erb  index.html.erb 
30c30
<   <%= link_to l(:button_delete), {:controller => 'periodictask', :action => 'destroy', :id => a.id, :project_id => @project}, :confirm => l(:text_are_you_sure), :method => :post, :class => 'icon icon-del' %>
---
>   <%= link_to l(:button_delete), {:controller => 'periodictask', :action => 'destroy', :id => a.id, :project_id => @project}, :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %>
```

**Comment by jperelli** [comment]
ok, can you tell me in which OS, browser and which http server are you using? (In which combinations you tested it and worked ok)

Because some combinations of those, may not accept a "delete" method, I think that is why it was "post" earlier, but in some commit (https://github.com/jperelli/Redmine-Periodic-Task/commit/f99658d5e9ff763aaf5be0bb1b2f05c571b4dfd3#diff-21497849d8f00507c9c8dcaf6288b136R21) this was changed to be more "restful" and introdced "delete" method.

Tipically there are problems with firewalls and/or proxies that only allow GET and POST verbs. So I think we should think about wich approach to take here.

If you make a pull request with this change, I'll merge it. It seems a good fix for now. I can make the change directly, but if you do the pull req, then you will be listed in contrubitors. So I think you should do a pull req.

**Comment by marczona** [comment]
Client-OS: Desktop Ubuntu 14.04.2 LTS
Browser: Mozilla Firefox 38.0 

Server-OS: Server Ubuntu 14.04.2 LTS
Http-Sever: Apache/2.4.7 (Ubuntu)

Both systems running as virtual machines, hosted by Oracle VirtualBox in Windows 7.
The used virtual network does not have any restrictions (firewall...)

**Comment by jperelli** [comment]
Ok, thank you! closing by pull req https://github.com/jperelli/Redmine-Periodic-Task/pull/22
